wandb_version: 1

setting:
  desc: null
  value:
    seed: 20000812
    ROOTDIR: ./
    os_environ:
      WANDB_API_KEY: 4cf78fcc7f33e9c70730eeb2f983cbc04b4bb9cd
      WANDB_RUN_ID: null
      CUDA_VISIBLE_DEVICES: 0,1,2,3,4,5,6,7
      MASTER_ADDR: localhost
      MASTER_PORT: 12315
    wandb_config:
      project: GO_CC
      name: BFN_650M
    tensorboard_config:
      save_dir: ./tensorboard/
      name: GO_CC
      version: GO_CC
      log_graph: false
      default_hp_metric: true
      prefix: ''
model_checkpoint:
  desc: null
  value:
    monitor: valid/valid_f1_max
    mode: max
    save_top_k: 1
    save_last: true
    verbose: true
    dirpath: checkpoints/GO/CC_trainGO/CC_BFN
    filename: valid_f1_max_{valid/valid_f1_max:.5f}
    auto_insert_metric_name: false
    every_n_train_steps: 0
    every_n_epochs: 1
model:
  desc: null
  value:
    model_py_path: bfn/bfn_annotation_model
    kwargs:
      net_name: /sharefs/gongjj/accounting/gongjj_dev_bfn4prot/bfn_650M_b2m_fromESM_16a100/27ea3bd_18159/
      load_pretrained: true
      anno_type: GO_CC
      load_prev_scheduler: true
      save_top_k: 1
      freeze_backbone: false
      dropout: 0.0
      use_lora: false
    lr_scheduler_kwargs:
      last_epoch: -1
      init_lr: 1.5e-05
      on_use: false
    optimizer_kwargs:
      betas:
      - 0.9
      - 0.98
      weight_decay: 0.01
    save_path: checkpoints/GO/CC_trainGO/CC_BFN
dataset:
  desc: null
  value:
    dataset_py_path: bfn/bfn_annotation_dataset
    dataloader_kwargs:
      batch_size: 1
      num_workers: 8
    train_lmdb: ./LMDB/GO/AF2/CC/normal/train
    valid_lmdb: ./LMDB/GO/AF2/CC/normal/test
    test_lmdb: ./LMDB/GO/AF2/CC/normal/test
    kwargs:
      tokenizer: /sharefs/gongjj/accounting/gongjj_dev_bfn4prot/bfn_650M_b2m_fromESM_16a100/27ea3bd_18159/
Trainer:
  desc: null
  value:
    max_epochs: 100
    log_every_n_steps: 1
    strategy:
      find_unused_parameters: true
    logger: wandb
    val_check_interval: 1.0
    accelerator: gpu
    devices: auto
    num_nodes: 1
    accumulate_grad_batches: 8
    precision: 16
    num_sanity_val_steps: 0
_wandb:
  desc: null
  value:
    python_version: 3.9.17
    cli_version: 0.16.6
    framework: huggingface
    huggingface_version: 4.28.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1733137775.0
    t:
      1:
      - 1
      - 5
      - 9
      - 11
      - 41
      - 49
      - 50
      - 53
      - 55
      - 64
      - 71
      - 98
      - 103
      2:
      - 1
      - 5
      - 9
      - 11
      - 41
      - 49
      - 50
      - 53
      - 55
      - 64
      - 71
      - 98
      - 103
      3:
      - 7
      - 13
      - 16
      - 23
      4: 3.9.17
      5: 0.16.6
      6: 4.28.0
      8:
      - 6
      13: linux-x86_64
    m:
    - 1: trainer/global_step
      6:
      - 3
